### ISSUE TITLE
highcharts draggable-points conflict between drag and click

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/draggable-points#15]
Related topic: http://stackoverflow.com/questions/26861680/highcharts-draggable-points-conflict-between-drag-and-click

**Comment by jam13c** [comment]
Hi, a variant of this issue appears to have resurfaced. The simple step of also including customEvents.js plugin appear to stop the drag and drop events from firing for draggable (although visually it still works).

Examples:

A simple draggable-only chart: https://jsfiddle.net/o09s0a1a/
Simply also including the code for customEvents: https://jsfiddle.net/x9xepr9q/

The series will still drag, but the console output when dropped no longer occurs.

**Comment by ajeantet** [comment]
I confirm that this issue is back.
Do you know how to solve it ?

**Comment by ajeantet** [comment]
Actually, things seem to be a bit more tricky : The conflict only involves elements which are within the Chart. In other words, if I try to trigger a click on an element anywhere outside of the chart on my page, it will work even if I've used the dragging. 
Conversely, if the div is part of the chart (for example it wraps a label) then using the drag and drop creates a conflict and it's no longer possible to fire a click event on the div.
Here is an example : https://jsfiddle.net/AJeantet/pu561k76/10/

**Comment by ajeantet** [comment]
A workaround is described here : https://stackoverflow.com/questions/45196140/highcharts-click-event-not-detected-after-a-redraw/45196641#45196641
