### ISSUE TITLE
draggable area range

### ISSUE THREAD

**Issue by likwifi** [highcharts/draggable-points#45]
Please implement logic for draggable arearange 

http://jsfiddle.net/249e3gk6/4/

**Comment by TorsteinHonsi** [comment]
_Internal note:_

The proposed fix adds support from low/high series. The decision of which point to move is based on which one is closest to the mouse drag. If we implement this in the plugin, we should also consider making it more general, so it can be used with OHLC, box plots etc.

**Comment by Izothep** [comment]
Hi,

I have added similar functionality to draggable-points plugin in this forum topic:
http://forum.highcharts.com/highstock-usage/draggable-arearange-t35193/?hilit=draggable

Here you can see an example how it can work (and changed code):
http://jsfiddle.net/249e3gk6/4/

Kind regards.

**Comment by sebastianzillessen** [comment]
This would be a really great feature. Any ETA on that?
Looks like the code already "exists" and it could be integrated easily.

**Comment by sebastianzillessen** [comment]
I think this can now be closed because of #62
