### ISSUE TITLE
Points not dropping?

### ISSUE THREAD

**Issue by Kozakewycz86** [highcharts/draggable-points#47]
Hi Torstein, I have encountered a problem in that the drop event has stopped working on all of  my draggable points charts.

I can grab a point and drag it about, but when I try and drop it, it continues to drag about. Leaving the chart area stops the dragging, but the point remains selected and the only way to deselect a point is to select another point, but then the problem repeats. This has happened to various unrelated charts stored in different folders.

Any advice on what could be causing this sort of problem?

**Comment by TorsteinHonsi** [comment]
Thanks for writing. Can you reproduce it on jsFiddle?

**Comment by Kozakewycz86** [comment]
I tried but I've never created one before and couldn't get my chart to work, it may be because it uses some backend PHP.

I will try again tonight but an example of the problem can be seen here.

http://blackartdynamics.com/bagshopify/draggable_points/

(Sorry I am a complete amateur when it comes to this sort of thing!)

**Comment by TorsteinHonsi** [comment]
No problem, maybe we don't need a jsFiddle demo. 

The first thing you should do is to upgrade Highcharts to the latest version.

**Comment by Kozakewycz86** [comment]
Hi Torstein, sorry for the slow response, got a new laptop and had issues getting the localhost working!

I updated to the latest version and that seems to have fixed it! It's great it turned out to be so simple, I had assumed it was something I did as it was working and then suddenly stopped!

Keep up the good work! :)

**Comment by TorsteinHonsi** [comment]
You're welcome!
