### ISSUE TITLE
point select issues

### ISSUE THREAD

**Issue by keithmdragon** [highcharts/draggable-points#48]
http://jsfiddle.net/kdragon/1d4sz5xs/5/

click on points and point labels, notice that point select sometimes happens to the wrong point. 

here are specific steps to make it happen, but lots of other ways too: run the fiddle, click 111 label, click 222 label -> point 111 is selected instead of point 222

also, notice some weird point fillColor. sometimes the fillColor is the series color, other times it's the point's manually assigned color. sometimes this is when selected, sometimes when not selected. keep clicking on the same point to see this. this only happens when the draggable.js is included

comment out the draggable.js and notice how this works correctly. seems like it is similar to this other issue that i reported that was corrected: https://github.com/highcharts/draggable-points/issues/43

in my actual app, the issue is, points that i am selecting become unselected. but just when i click on their labels. something is firing after i select the point.

chrome on windows 7 64

Thanks
Keith

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, I fixed it by adding a new option, `dragSensitivity`, that defaults to 1. It prevents drag/drop from happening when clicking points.
