### ISSUE TITLE
Setting draggableX = false on first or last points disables Y draggable

### ISSUE THREAD

**Issue by frijj2k** [highcharts/draggable-points#49]
Setting draggableX = false on the first or last points in series data prevents dragging in the Y axis also.

I am using an 'area' chart type and call the following to change the point options:

`var firstPoint = chart.series[0].data[0];`
`var lastPoint = chart.series[0].data[chart.series[0].data.length - 1];`
`firstPoint.draggableX = false;`
`lastPoint.draggableX = false;`

All other points are unaffacted, just the first and last points become 'fixed' in place.

**Comment by TorsteinHonsi** [comment]
#### Live demo:
http://jsfiddle.net/highcharts/AyUbx/3227/

**Comment by frijj2k** [comment]
Hi, Just tested the demo and the problem till persists for me...  Tried in Firefox and Safari (with clean cache).  :(

**Comment by TorsteinHonsi** [comment]
I'ts probably rawgithub.com's cache. Try http://jsfiddle.net/highcharts/AyUbx/3229/.

**Comment by frijj2k** [comment]
Yes, it's working now! Many thanks!  :)
