### ISSUE TITLE
Plug-in stopped working

### ISSUE THREAD

**Issue by Zohaib9** [highcharts/draggable-points#67]
Hi,

I've been using the draggable-points plug-in, and it has been working fine. It recently stopped working (no code change on my side). I've checked on multiple browsers/PCs. Even the provided demos are not working anymore.

Can you please comment on the issue?

-Z

**Comment by sebastianbochan** [comment]
It works properly in the simple demo: https://jsfiddle.net/zta9dub5/. Could you update my code with yours for the further debugging?

**Comment by Zohaib9** [comment]
Thank you Sebastian! Changing 
https://rawgithub.com/.../draggable-points.js 
to 
https://rawgit.com/.../draggable-points.js
solves the issue.
