### ISSUE TITLE
Support for draggable plotLines

### ISSUE THREAD

**Issue by christianknu** [highcharts/draggable-points#72]
Would it be possible to add support for dragging plotLines?

**Comment by sebastianbochan** [comment]
Hi @christianknu,
Currently this is not a part of a draggable-points package, but you can use a workaround:
- http://jsfiddle.net/VXTeR/1/

**Comment by christianknu** [comment]
Hi @sebastianbochan,
Yes, I stumpled upon that example and will try and implement it - thanks.
