### ISSUE TITLE
Option to enable/disable mouseleave event listener

### ISSUE THREAD

**Issue by ZachMilne** [highcharts/draggable-points#76]
If the mouse inadvertently leaves the chart container while dragging, an undesirable drop event occurs. I propose a dropOnMouseleave option. Default: true

**Comment by pawelfus** [comment]
Thank you for the suggestion.

At this moment it's possible to unbind Highcharts events in `chart.events.load` callback, for example: https://jsfiddle.net/15xkuykt/

```
  chart: {
    renderTo: 'container',
    events: {
      load: function() {
      
        Highcharts.removeEvent(
          this.container,
          'mouseleave',
          Highcharts.grep(
            this.container.hcEvents.mouseleave,
            function(fun) {
              return this.name === 'drop'; // draggable point adds "drop" function
            }
          )[0]
        );
        
      }
    }
  },
```

The only problem is that index for `mouseleave`

**Comment by TorsteinHonsi** [comment]
I just did a change I've been planning already - to allow returning false from the `drop` event handler to cancel the drop. Now you can check the event arguments to cancel in your case:

```js
                        if (e.originalEvent.type === 'mouseleave') {
                            return false;
                        }
```

https://jsfiddle.net/highcharts/15xkuykt/2/

**Comment by ZachMilne** [comment]
That will work well. Thanks for the quick responses and implementation.
