### ISSUE TITLE
Abnormal behavior on drag to negative value in column chart

### ISSUE THREAD

**Issue by MercusChan** [highcharts/draggable-points#78]
sometimes can't drag or can't drop

seems not yet support

**Comment by pawelfus** [comment]
It looks like drag handler is mispositioned: http://jsfiddle.net/AyUbx/3816/ but dragging looks fine. Could you recreate issue in jsFiddle?

**Comment by sebastianbochan** [comment]
Hi @MercusChan Do you mean that handler does not move on negative bars or Im wrong?

**Comment by MercusChan** [comment]
Hi @sebastianbochan 
Base on the example from @pawelfus, I only found the problem on drag handler is mispositioned.

**Comment by MercusChan** [comment]
Found how to repeat after added column: {
            stacking: 'normal'
        }
under plotOptions

http://jsfiddle.net/AyUbx/3820/

**Comment by MercusChan** [comment]
@pawelfus 
any progress on fix?

**Comment by KacperMadej** [comment]
@MercusChan Both problems should be now resolved.
