### ISSUE TITLE
Drag handler is missing when value = 0

### ISSUE THREAD

**Issue by MercusChan** [highcharts/draggable-points#79]
See this example
http://jsfiddle.net/AyUbx/3825/

Thank you.

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug.

The problem is caused by column being too small, so you could resolve the issue by setting [minPointLength](https://api.highcharts.com/highcharts/series.column.minPointLength). Demo: http://jsfiddle.net/BlackLabel/AyUbx/3831/

**Comment by MercusChan** [comment]
Confirmed, thanks
