### ISSUE TITLE
how can i use this options??

### ISSUE THREAD

**Issue by rldbs925** [highcharts/draggable-points#81]
hello

i have one question

how can i use this options?

Options : 'plotOptions.series.data.draggableX' AND 'plotOptions.series.data.draggableY'
Description : 'If dragging is enabled on the series, set this to false to prevent dragging on a single point.'

can i take sample code about this options?

thank you

**Comment by pawelfus** [comment]
Hi @rldbs925 

You can find sample code from the official demos, for example: http://jsfiddle.net/highcharts/AyUbx/
