### ISSUE TITLE
switching between series while dragging?

### ISSUE THREAD

**Issue by raymar** [highcharts/draggable-points#82]
I have two draggable scatter points on a risk matrix (severe case and median case). Is there a way how to switch points being dragged if the severe case y axis value exceeds the median case y axis value?

![highcharts](https://user-images.githubusercontent.com/22484568/34470284-8d0f203c-ef2e-11e7-9b95-0452d5ead81f.PNG)

The white point cannot be greater than the black one...if it happens I want to change the dragged point. In other words if the user exceeds the severe case, he will be suddenly dragging the black one.

**Comment by TorsteinHonsi** [comment]
Not out of the box I'm afraid. You need to write your own logic in the `drag` and/or `drop` event handlers to accomplish this.
