### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by yanzou** [highcharts/draggable-points#85]
![image](https://user-images.githubusercontent.com/7699445/45455754-02ece380-b69d-11e8-8088-0e56ff0e2f8d.png)

https://github.com/highcharts/draggable-points/blob/master/draggable-points.js#L84
```js
function getNewPos(e) {
  ...
  dragSensitivity = pick(series.options.dragSensitiviy, 1),  // <-- series.options.dragSensitivity ?
```

**Comment by TorsteinHonsi** [comment]
Thanks @yanzou !
